baseURL = "https://e10s.github.io/"
languageCode = "en-us"
title = "e10s.github.io"

enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "RSS"]

[params]
hideRSSLink = true

[outputFormats]
[outputFormats.SitemapIndex]
name = "SitemapIndex"
baseName = "sitemap_index"
mediaType = "application/xml"
noUgly = true

[outputs]
home = ["HTML", "SitemapIndex"]

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10
[[menu.main]]
name = "Documents"
pageRef = "/docs/"
weight = 20

[module]
[[module.imports]]
path = "github.com/maolonglong/hugo-simple"
