baseURL = 'https://e10s.github.io/'
languageCode = 'en-us'
title = 'e10s.github.io'

enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "RSS"]

[params]
favicon = "images/favicon.png"
hideRSSLink = true

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10
[[menu.main]]
name = "Documents"
pageRef = "/docs/"
weight = 20

[module]
[[module.imports]]
path = "github.com/maolonglong/hugo-simple"
